export const TEN_LATEST_ITEM_REQUEST = 'TEN_LATEST_ITEM_REQUEST';
export const TEN_LATEST_ITEM_SUCCESS = 'TEN_LATEST_ITEM_SUCCESS';
export const TEN_LATEST_ITEM_FAIL = 'TEN_LATEST_ITEM_FAIL';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';

export const SELECTED_MENU = 'SELECTED_MENU';
export const REMOVE_SELECTED_MENU = 'REMOVE_SELECTED_MENU';